project:
  type: website
  output-dir: docs

website:
  title: "Seth Coetzee"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-location: right
    smooth-scroll: true
    code-fold: true
    date-format: "DD-MM-YYYY"

editor: visual
